// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: protocol.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_HANDSHAKE      MessageType = 0
	MessageType_HANDSHAKE_ACK  MessageType = 1
	MessageType_HEARTBEAT      MessageType = 2
	MessageType_HEARTBEAT_ACK  MessageType = 3
	MessageType_ACK            MessageType = 4
	MessageType_SEND_MESSAGE   MessageType = 10
	MessageType_RECV_MESSAGE   MessageType = 11
	MessageType_MESSAGE_READ   MessageType = 12
	MessageType_MESSAGE_RECALL MessageType = 13
	MessageType_TYPING         MessageType = 14
	MessageType_SYNC_REQUEST   MessageType = 20
	MessageType_SYNC_RESPONSE  MessageType = 21
	MessageType_FRIEND_REQUEST MessageType = 30
	MessageType_FRIEND_ACCEPT  MessageType = 31
	MessageType_GROUP_INVITE   MessageType = 32
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "HANDSHAKE",
		1:  "HANDSHAKE_ACK",
		2:  "HEARTBEAT",
		3:  "HEARTBEAT_ACK",
		4:  "ACK",
		10: "SEND_MESSAGE",
		11: "RECV_MESSAGE",
		12: "MESSAGE_READ",
		13: "MESSAGE_RECALL",
		14: "TYPING",
		20: "SYNC_REQUEST",
		21: "SYNC_RESPONSE",
		30: "FRIEND_REQUEST",
		31: "FRIEND_ACCEPT",
		32: "GROUP_INVITE",
	}
	MessageType_value = map[string]int32{
		"HANDSHAKE":      0,
		"HANDSHAKE_ACK":  1,
		"HEARTBEAT":      2,
		"HEARTBEAT_ACK":  3,
		"ACK":            4,
		"SEND_MESSAGE":   10,
		"RECV_MESSAGE":   11,
		"MESSAGE_READ":   12,
		"MESSAGE_RECALL": 13,
		"TYPING":         14,
		"SYNC_REQUEST":   20,
		"SYNC_RESPONSE":  21,
		"FRIEND_REQUEST": 30,
		"FRIEND_ACCEPT":  31,
		"GROUP_INVITE":   32,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

type ChatType int32

const (
	ChatType_SINGLE ChatType = 0
	ChatType_GROUP  ChatType = 1
)

// Enum value maps for ChatType.
var (
	ChatType_name = map[int32]string{
		0: "SINGLE",
		1: "GROUP",
	}
	ChatType_value = map[string]int32{
		"SINGLE": 0,
		"GROUP":  1,
	}
)

func (x ChatType) Enum() *ChatType {
	p := new(ChatType)
	*p = x
	return p
}

func (x ChatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[1].Descriptor()
}

func (ChatType) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[1]
}

func (x ChatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatType.Descriptor instead.
func (ChatType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

type ContentType int32

const (
	ContentType_TEXT  ContentType = 0
	ContentType_IMAGE ContentType = 1
	ContentType_VOICE ContentType = 2
	ContentType_FILE  ContentType = 3
	ContentType_VIDEO ContentType = 4
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "VOICE",
		3: "FILE",
		4: "VIDEO",
	}
	ContentType_value = map[string]int32{
		"TEXT":  0,
		"IMAGE": 1,
		"VOICE": 2,
		"FILE":  3,
		"VIDEO": 4,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[2].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[2]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

// Envelope 消息信封 - 所有 WS 消息的外层包装
type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           int64                  `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_HANDSHAKE
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HandshakeRequest 握手认证
type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"` // android / windows
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HandshakeRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HandshakeRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// HandshakeAckResponse 握手响应
type HandshakeAckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	LastSeq       int64                  `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeAckResponse) Reset() {
	*x = HandshakeAckResponse{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeAckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeAckResponse) ProtoMessage() {}

func (x *HandshakeAckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeAckResponse.ProtoReflect.Descriptor instead.
func (*HandshakeAckResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeAckResponse) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *HandshakeAckResponse) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// ChatMessage 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	FromUid       int64                  `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	ToId          string                 `protobuf:"bytes,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ChatType      ChatType               `protobuf:"varint,4,opt,name=chat_type,json=chatType,proto3,enum=protocol.ChatType" json:"chat_type,omitempty"`
	ContentType   ContentType            `protobuf:"varint,5,opt,name=content_type,json=contentType,proto3,enum=protocol.ContentType" json:"content_type,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ChatMessage) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *ChatMessage) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *ChatMessage) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_SINGLE
}

func (x *ChatMessage) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_TEXT
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// SendMessageRequest 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToId          string                 `protobuf:"bytes,1,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ChatType      ChatType               `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=protocol.ChatType" json:"chat_type,omitempty"`
	ContentType   ContentType            `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3,enum=protocol.ContentType" json:"content_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ReplyTo       string                 `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *SendMessageRequest) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_SINGLE
}

func (x *SendMessageRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_TEXT
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

// SyncRequest 离线同步请求
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSeq       int64                  `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *SyncRequest) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SyncRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SyncResponse 离线同步响应
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *SyncResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// AckRequest 确认收到
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSeq       int64                  `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *AckRequest) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

// TypingRequest 输入中状态
type TypingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToId          string                 `protobuf:"bytes,1,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ChatType      ChatType               `protobuf:"varint,2,opt,name=chat_type,json=chatType,proto3,enum=protocol.ChatType" json:"chat_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingRequest) Reset() {
	*x = TypingRequest{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingRequest) ProtoMessage() {}

func (x *TypingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingRequest.ProtoReflect.Descriptor instead.
func (*TypingRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *TypingRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *TypingRequest) GetChatType() ChatType {
	if x != nil {
		return x.ChatType
	}
	return ChatType_SINGLE
}

// FriendRequestNotify 好友申请通知
type FriendRequestNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUid       int64                  `protobuf:"varint,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`
	FromNickname  string                 `protobuf:"bytes,2,opt,name=from_nickname,json=fromNickname,proto3" json:"from_nickname,omitempty"`
	FromAvatar    string                 `protobuf:"bytes,3,opt,name=from_avatar,json=fromAvatar,proto3" json:"from_avatar,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	RequestId     int64                  `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestNotify) Reset() {
	*x = FriendRequestNotify{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestNotify) ProtoMessage() {}

func (x *FriendRequestNotify) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestNotify.ProtoReflect.Descriptor instead.
func (*FriendRequestNotify) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *FriendRequestNotify) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *FriendRequestNotify) GetFromNickname() string {
	if x != nil {
		return x.FromNickname
	}
	return ""
}

func (x *FriendRequestNotify) GetFromAvatar() string {
	if x != nil {
		return x.FromAvatar
	}
	return ""
}

func (x *FriendRequestNotify) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FriendRequestNotify) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

// MessageReadRequest 已读通知
type MessageReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,2,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageReadRequest) Reset() {
	*x = MessageReadRequest{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReadRequest) ProtoMessage() {}

func (x *MessageReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReadRequest.ProtoReflect.Descriptor instead.
func (*MessageReadRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *MessageReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageReadRequest) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

// MessageRecallRequest 撤回消息
type MessageRecallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRecallRequest) Reset() {
	*x = MessageRecallRequest{}
	mi := &file_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRecallRequest) ProtoMessage() {}

func (x *MessageRecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRecallRequest.ProtoReflect.Descriptor instead.
func (*MessageRecallRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *MessageRecallRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\bprotocol\"\x7f\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x03R\x03seq\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"a\n" +
	"\x10HandshakeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\"C\n" +
	"\x14HandshakeAckResponse\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x03R\alastSeq\"\x93\x02\n" +
	"\vChatMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x19\n" +
	"\bfrom_uid\x18\x02 \x01(\x03R\afromUid\x12\x13\n" +
	"\x05to_id\x18\x03 \x01(\tR\x04toId\x12/\n" +
	"\tchat_type\x18\x04 \x01(\x0e2\x12.protocol.ChatTypeR\bchatType\x128\n" +
	"\fcontent_type\x18\x05 \x01(\x0e2\x15.protocol.ContentTypeR\vcontentType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x19\n" +
	"\breply_to\x18\a \x01(\tR\areplyTo\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\xc9\x01\n" +
	"\x12SendMessageRequest\x12\x13\n" +
	"\x05to_id\x18\x01 \x01(\tR\x04toId\x12/\n" +
	"\tchat_type\x18\x02 \x01(\x0e2\x12.protocol.ChatTypeR\bchatType\x128\n" +
	"\fcontent_type\x18\x03 \x01(\x0e2\x15.protocol.ContentTypeR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\breply_to\x18\x05 \x01(\tR\areplyTo\">\n" +
	"\vSyncRequest\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x03R\alastSeq\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\\\n" +
	"\fSyncResponse\x121\n" +
	"\bmessages\x18\x01 \x03(\v2\x15.protocol.ChatMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"'\n" +
	"\n" +
	"AckRequest\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x03R\alastSeq\"U\n" +
	"\rTypingRequest\x12\x13\n" +
	"\x05to_id\x18\x01 \x01(\tR\x04toId\x12/\n" +
	"\tchat_type\x18\x02 \x01(\x0e2\x12.protocol.ChatTypeR\bchatType\"\xaf\x01\n" +
	"\x13FriendRequestNotify\x12\x19\n" +
	"\bfrom_uid\x18\x01 \x01(\x03R\afromUid\x12#\n" +
	"\rfrom_nickname\x18\x02 \x01(\tR\ffromNickname\x12\x1f\n" +
	"\vfrom_avatar\x18\x03 \x01(\tR\n" +
	"fromAvatar\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x03R\trequestId\"a\n" +
	"\x12MessageReadRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x02 \x01(\x03R\vlastReadSeq\"-\n" +
	"\x14MessageRecallRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId*\x8e\x02\n" +
	"\vMessageType\x12\r\n" +
	"\tHANDSHAKE\x10\x00\x12\x11\n" +
	"\rHANDSHAKE_ACK\x10\x01\x12\r\n" +
	"\tHEARTBEAT\x10\x02\x12\x11\n" +
	"\rHEARTBEAT_ACK\x10\x03\x12\a\n" +
	"\x03ACK\x10\x04\x12\x10\n" +
	"\fSEND_MESSAGE\x10\n" +
	"\x12\x10\n" +
	"\fRECV_MESSAGE\x10\v\x12\x10\n" +
	"\fMESSAGE_READ\x10\f\x12\x12\n" +
	"\x0eMESSAGE_RECALL\x10\r\x12\n" +
	"\n" +
	"\x06TYPING\x10\x0e\x12\x10\n" +
	"\fSYNC_REQUEST\x10\x14\x12\x11\n" +
	"\rSYNC_RESPONSE\x10\x15\x12\x12\n" +
	"\x0eFRIEND_REQUEST\x10\x1e\x12\x11\n" +
	"\rFRIEND_ACCEPT\x10\x1f\x12\x10\n" +
	"\fGROUP_INVITE\x10 *!\n" +
	"\bChatType\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01*B\n" +
	"\vContentType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VOICE\x10\x02\x12\b\n" +
	"\x04FILE\x10\x03\x12\t\n" +
	"\x05VIDEO\x10\x04B'Z%github.com/mychat/server/pkg/protocolb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protocol_proto_goTypes = []any{
	(MessageType)(0),             // 0: protocol.MessageType
	(ChatType)(0),                // 1: protocol.ChatType
	(ContentType)(0),             // 2: protocol.ContentType
	(*Envelope)(nil),             // 3: protocol.Envelope
	(*HandshakeRequest)(nil),     // 4: protocol.HandshakeRequest
	(*HandshakeAckResponse)(nil), // 5: protocol.HandshakeAckResponse
	(*ChatMessage)(nil),          // 6: protocol.ChatMessage
	(*SendMessageRequest)(nil),   // 7: protocol.SendMessageRequest
	(*SyncRequest)(nil),          // 8: protocol.SyncRequest
	(*SyncResponse)(nil),         // 9: protocol.SyncResponse
	(*AckRequest)(nil),           // 10: protocol.AckRequest
	(*TypingRequest)(nil),        // 11: protocol.TypingRequest
	(*FriendRequestNotify)(nil),  // 12: protocol.FriendRequestNotify
	(*MessageReadRequest)(nil),   // 13: protocol.MessageReadRequest
	(*MessageRecallRequest)(nil), // 14: protocol.MessageRecallRequest
}
var file_protocol_proto_depIdxs = []int32{
	0, // 0: protocol.Envelope.type:type_name -> protocol.MessageType
	1, // 1: protocol.ChatMessage.chat_type:type_name -> protocol.ChatType
	2, // 2: protocol.ChatMessage.content_type:type_name -> protocol.ContentType
	1, // 3: protocol.SendMessageRequest.chat_type:type_name -> protocol.ChatType
	2, // 4: protocol.SendMessageRequest.content_type:type_name -> protocol.ContentType
	6, // 5: protocol.SyncResponse.messages:type_name -> protocol.ChatMessage
	1, // 6: protocol.TypingRequest.chat_type:type_name -> protocol.ChatType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
